### ISSUE TITLE
Hypercore Protocol Implementation?

### ISSUE THREAD

**Issue by jwerle** [mafintosh/libdat#1]
This is great! Instead of starting this high level, perhaps we can start with a hypercore protocol implementation?

**Comment by creationix** [comment]
There are lots of places to start.  I don't think the order really matters since we eventually need them all for most use cases and they can be developed in parallel.

**Comment by jwerle** [comment]
Sure, that makes sense. I may take a stab at a hypercore protocol implementation as it is something we already have considered building ourselves and will need for use cases. Hyperdrive would follow next
